name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.js'
      - 'package.json'
      - '**/*.njk'
      - '**/*.yml'
      - 'tests/**/*.html'

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
      - run: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      - run: npm test
      # Commented out until this action is added in organization settings
      # - name: Report coverage
      #   if: success()
      #   uses: codecov/codecov-action@v1
